# Jeroens opencpu CI deb builder

language: R
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    sources:
    - sourceline: 'ppa:opencpu/rapache'
    packages:
    - devscripts
    - equivs
    - gdebi-core

before_install:
  - sudo mk-build-deps -i

install:
  - echo "DEBUILD_TGZ_CHECK=no" >> ~/.devscripts
  - debuild -us -uc
  - sudo gdebi --n ../opencpu-lib_*.deb
  - sudo gdebi --n ../opencpu-server_*.deb  
  - sudo gdebi --n ../opencpu-cache_*.deb

script: sudo service opencpu restart

after_failure:

notifications:
  email:
    on_success: change
    on_failure: change
