# Jeroens opencpu CI deb builder

language: generic
sudo: required
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'ppa:marutter/rrutter3.5'
    - sourceline: 'ppa:opencpu/rapache'
    - sourceline: 'ppa:nginx/stable'
    packages:
    - curl
    - devscripts
    - equivs
    - gdebi-core

before_install:
  - sudo mk-build-deps -i

install:
  - echo "DEBUILD_TGZ_CHECK=no" >> ~/.devscripts
  - debuild -us -uc
  - sudo gdebi --n ../opencpu-lib_*.deb
  - sudo gdebi --n ../opencpu-server_*.deb  
  - sudo gdebi --n ../opencpu-cache_*.deb
  - sudo apt-get remove -y opencpu-cache

script:
  - curl -m5 http://localhost/ocpu/info

after_script:
  sudo cat /var/log/apache2/error.log

notifications:
  email:
    on_success: change
    on_failure: change
