# Jeroens opencpu CI deb builder
# Builds and installs the opencpu cloud server

language: c

before_install:
  - sudo add-apt-repository -y ppa:opencpu/rapache
  - sudo add-apt-repository -y ppa:marutter/c2d4u
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install devscripts equivs gdebi-core
  - sudo mk-build-deps -i
install:
  - echo "DEBUILD_TGZ_CHECK=no" >> ~/.devscripts
  - debuild -us -uc
  - sudo gdebi --n ../opencpu-lib_*.deb
  - sudo gdebi --n ../opencpu-server_*.deb  
  - sudo gdebi --n ../opencpu-cache_*.deb
script: sudo service opencpu restart

after_failure:

notifications:
  email:
    on_success: change
    on_failure: change
